// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_estep_ltm_cpp
List compute_estep_ltm_cpp(IntegerVector row_ptr, IntegerVector col_idx, IntegerVector values, NumericVector alpha, NumericVector beta, NumericVector theta_ls, NumericVector qw_ls, NumericVector fitted_mean, NumericVector fitted_var);
RcppExport SEXP _hIRT_compute_estep_ltm_cpp(SEXP row_ptrSEXP, SEXP col_idxSEXP, SEXP valuesSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP theta_lsSEXP, SEXP qw_lsSEXP, SEXP fitted_meanSEXP, SEXP fitted_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type row_ptr(row_ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type col_idx(col_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta_ls(theta_lsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type qw_ls(qw_lsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fitted_mean(fitted_meanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fitted_var(fitted_varSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_estep_ltm_cpp(row_ptr, col_idx, values, alpha, beta, theta_ls, qw_ls, fitted_mean, fitted_var));
    return rcpp_result_gen;
END_RCPP
}
// compute_mstep_ltm_cpp
List compute_mstep_ltm_cpp(IntegerVector row_ptr, IntegerVector col_idx, IntegerVector values, NumericMatrix w, NumericVector theta_ls, NumericVector alpha_init, NumericVector beta_init, int max_nr_iter, double nr_tol, double mu_prior, double sigma_prior);
RcppExport SEXP _hIRT_compute_mstep_ltm_cpp(SEXP row_ptrSEXP, SEXP col_idxSEXP, SEXP valuesSEXP, SEXP wSEXP, SEXP theta_lsSEXP, SEXP alpha_initSEXP, SEXP beta_initSEXP, SEXP max_nr_iterSEXP, SEXP nr_tolSEXP, SEXP mu_priorSEXP, SEXP sigma_priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type row_ptr(row_ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type col_idx(col_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta_ls(theta_lsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha_init(alpha_initSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_init(beta_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_nr_iter(max_nr_iterSEXP);
    Rcpp::traits::input_parameter< double >::type nr_tol(nr_tolSEXP);
    Rcpp::traits::input_parameter< double >::type mu_prior(mu_priorSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_prior(sigma_priorSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_mstep_ltm_cpp(row_ptr, col_idx, values, w, theta_ls, alpha_init, beta_init, max_nr_iter, nr_tol, mu_prior, sigma_prior));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hIRT_compute_estep_ltm_cpp", (DL_FUNC) &_hIRT_compute_estep_ltm_cpp, 9},
    {"_hIRT_compute_mstep_ltm_cpp", (DL_FUNC) &_hIRT_compute_mstep_ltm_cpp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_hIRT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
